"""[PREVALENCE] Social and administrative condition codes, versioned and attributed.

Synthea writes some codes to ``conditions.csv`` that are not diseases: the answers of the
social determinants of health screening (employment, education, stress, social isolation,
violence, housing, transport…) and an administrative marker (``Medication review due``).
In the sample they head the list of the most common conditions, so a general prevalence
table would open with employment status instead of disease.

The general table leaves them out **by default** and says so; ``--include-social`` puts
them back. Conditions asked for by code are never filtered. If the Synthea maintainers
advise otherwise, only this list or that default changes.

How the list is built
---------------------
Not from the SNOMED semantic tag: ``(finding)`` would also remove clinical findings such
as Prediabetes and obesity, and would keep ``Medication review due (situation)`` and
``Refugee (person)``. Instead, the list is every code a ``ConditionOnset`` state writes
in two modules, extracted mechanically by ``scripts/extract_social_codes.py`` from
Synthea commit ``d9d07a6e`` (the commit that generated the official sample; the modules
are unchanged at ``44f645c``):

* ``encounter/sdoh_hrsn.json`` — "SDoH HRSN" screening (20 codes);
* ``med_rec.json`` — "Medication Reconciliation" (1 code).

Each entry records every module that writes the code, so a code shared with another
module (``Homeless`` with ``homelessness.json``, ``Victim of intimate partner abuse``
with ``hark_screening.json``) shows it. Substance use and anxiety screening findings are
clinical and stay in the table.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from synthea_quality.prevalence.models import normalise_system

#: Identifier of this version of the list, recorded in every report.
SOCIAL_LIST_ID = "synthea-d9d07a6e-social-1"
#: Synthea commit the list was extracted from.
SYNTHEA_COMMIT = "d9d07a6e"
#: Modules whose condition codes form the list.
SOURCE_MODULES = ("encounter/sdoh_hrsn.json", "med_rec.json")


@dataclass(frozen=True, slots=True)
class SocialCode:
    """One code of the list, with the module files that write it."""

    code: str
    display: str
    system: str
    modules: tuple[str, ...]

    @property
    def key(self) -> tuple[str | None, str]:
        return normalise_system(self.system), self.code


# Generated by: python scripts/extract_social_codes.py <synthea checkout at d9d07a6e>
SOCIAL_CODES: tuple[SocialCode, ...] = (
    SocialCode(
        "473461003",
        "Educated to high school level (finding)",
        "SNOMED-CT",
        ("encounter/sdoh_hrsn.json",),
    ),
    SocialCode(
        "160903007",
        "Full-time employment (finding)",
        "SNOMED-CT",
        ("encounter/sdoh_hrsn.json",),
    ),
    SocialCode(
        "266948004",
        "Has a criminal record (finding)",
        "SNOMED-CT",
        ("encounter/sdoh_hrsn.json",),
    ),
    SocialCode(
        "32911000",
        "Homeless (finding)",
        "SNOMED-CT",
        ("encounter/sdoh_hrsn.json", "homelessness.json",),
    ),
    SocialCode(
        "105531004",
        "Housing unsatisfactory (finding)",
        "SNOMED-CT",
        ("encounter/sdoh_hrsn.json",),
    ),
    SocialCode(
        "713458007",
        "Lack of access to transportation (finding)",
        "SNOMED-CT",
        ("encounter/sdoh_hrsn.json",),
    ),
    SocialCode(
        "423315002",
        "Limited social contact (finding)",
        "SNOMED-CT",
        ("encounter/sdoh_hrsn.json",),
    ),
    SocialCode(
        "314529007",
        "Medication review due (situation)",
        "SNOMED-CT",
        ("med_rec.json",),
    ),
    SocialCode(
        "741062008",
        "Not in labor force (finding)",
        "SNOMED-CT",
        ("encounter/sdoh_hrsn.json",),
    ),
    SocialCode(
        "224295006",
        "Only received primary school education (finding)",
        "SNOMED-CT",
        ("encounter/sdoh_hrsn.json",),
    ),
    SocialCode(
        "160904001",
        "Part-time employment (finding)",
        "SNOMED-CT",
        ("encounter/sdoh_hrsn.json",),
    ),
    SocialCode(
        "224299000",
        "Received higher education (finding)",
        "SNOMED-CT",
        ("encounter/sdoh_hrsn.json",),
    ),
    SocialCode(
        "446654005",
        "Refugee (person)",
        "SNOMED-CT",
        ("encounter/sdoh_hrsn.json",),
    ),
    SocialCode(
        "424393004",
        "Reports of violence in the environment (finding)",
        "SNOMED-CT",
        ("encounter/sdoh_hrsn.json",),
    ),
    SocialCode(
        "1187604002",
        "Serving in military service (finding)",
        "SNOMED-CT",
        ("encounter/sdoh_hrsn.json",),
    ),
    SocialCode(
        "422650009",
        "Social isolation (finding)",
        "SNOMED-CT",
        ("encounter/sdoh_hrsn.json",),
    ),
    SocialCode(
        "160701002",
        "Social migrant (finding)",
        "SNOMED-CT",
        ("encounter/sdoh_hrsn.json",),
    ),
    SocialCode(
        "73595000",
        "Stress (finding)",
        "SNOMED-CT",
        ("encounter/sdoh_hrsn.json",),
    ),
    SocialCode(
        "266934004",
        "Transport problem (finding)",
        "SNOMED-CT",
        ("encounter/sdoh_hrsn.json",),
    ),
    SocialCode(
        "73438004",
        "Unemployed (finding)",
        "SNOMED-CT",
        ("encounter/sdoh_hrsn.json",),
    ),
    SocialCode(
        "706893006",
        "Victim of intimate partner abuse (finding)",
        "SNOMED-CT",
        ("encounter/sdoh_hrsn.json", "encounter/hark_screening.json",),
    ),
)

_KEYS = frozenset(entry.key for entry in SOCIAL_CODES)


def is_social(system: str | None, code: str) -> bool:
    """Whether ``(system, code)`` is on the list; a missing system matches by code alone."""
    if system is None:
        return any(code == entry.code for entry in SOCIAL_CODES)
    return (normalise_system(system), code) in _KEYS


def describe_list() -> dict[str, Any]:
    """The list's identity and provenance, as recorded in a report."""
    return {
        "id": SOCIAL_LIST_ID,
        "source": "built-in",
        "synthea_commit": SYNTHEA_COMMIT,
        "source_modules": list(SOURCE_MODULES),
        "codes": len(SOCIAL_CODES),
        "entries": [
            {
                "system": entry.system,
                "code": entry.code,
                "display": entry.display,
                "modules": list(entry.modules),
            }
            for entry in SOCIAL_CODES
        ],
    }
